-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 01, 2024 at 09:29 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `finall`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `Book Or Manuscript` text DEFAULT NULL,
  `Author` text DEFAULT NULL,
  `Image` text DEFAULT NULL,
  `Wikipedia Profile` text DEFAULT NULL,
  `Description` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`Book Or Manuscript`, `Author`, `Image`, `Wikipedia Profile`, `Description`) VALUES
('Action Comics 1', 'Jerry Siegel, Joe Shuster', 'http://upload.wikimedia.org/wikipedia/en/5/5a/Action_Comics_1.jpg', 'http://en.wikipedia.org/wiki/Action_Comics_1', 'Action Comics #1 (June 1938) is the first issue of the comic book series Action Comics. It features the first appearance of several comic book heroes—most notably the Jerry Siegel and Joe Shuster creation, Superman. For this reason it is widely considered both the beginning of the superhero genre and the most valuable comic book of all time. On August 24, 2014, a copy graded 9.0 by CGC was sold on eBay for US$3,207,852. It is the only comic to have sold for more than $3 million for a single original copy.'),
('Bay Psalm Book', 'Richard Mather', 'http://upload.wikimedia.org/wikipedia/commons/f/fc/Bay_Psalm_Book_LoC.png', 'http://en.wikipedia.org/wiki/Bay_Psalm_Book', 'The Bay Psalm Book was the first book printed in British North America. The book is a metrical Psalter, first printed in 1640 in Cambridge, Massachusetts. The Psalms in it are metrical translations into English. The translations are not particularly polished, and not one has remained in use, although some of the tunes to which they were sung have survived (for instance, \"Old 100th\"). However, its production, just 20 years after the Pilgrims arrival at Plymouth, Massachusetts, represents a considerable achievement. It went through several editions and remained in use for well over a century. One of eleven known surviving copies of the first edition sold at auction in November 2013 for $14.2 million, a record for a printed book.'),
('Biblia pauperum', '-', 'http://upload.wikimedia.org/wikipedia/commons/4/41/BibliaPauperum.jpg', 'http://en.wikipedia.org/wiki/Biblia_pauperum', 'The Biblia pauperum (\"Paupers Bible\") was a tradition of picture Bibles beginning probably with Ansgar, and a common printed block-book in the later Middle Ages to visualize the typological correspondences between the Old and New Testaments. Unlike a simple \"illustrated Bible\", where the pictures are subordinated to the text, these Bibles placed the illustration in the centre, with only a brief text or sometimes no text at all. Words spoken by the figures in the miniatures could be written on scrolls coming out of their mouths. To this extent one might see parallels with modern cartoon strips.'),
('Codex Leicester - Original and only copy of the notebook', 'Leonardo da Vinci', 'http://upload.wikimedia.org/wikipedia/commons/6/60/Vinci_-_Hammer_2A.jpg', 'http://en.wikipedia.org/wiki/Codex_Leicester', 'The Codex Leicester (also briefly known as Codex Hammer) is a collection of largely scientific writings by Leonardo da Vinci. The codex is named after Thomas Coke, later created Earl of Leicester, who purchased it in 1719. Of Leonardos 30 scientific journals, the Codex may be the most famous of all. The manuscript holds the record for the sale price of any book, when it was sold to Bill Gates at Christies auction house on 11 November 1994 in New York for US$30,802,500.'),
('Complete Folio of Birds', 'John Gould', 'http://www.guernseys.com/images/john_gould_books.png', '', 'The Birds of America is a book by naturalist and painter John James Audubon, containing illustrations of a wide variety of birds of the United States. It was first published as a series in sections between 1827 and 1838, in Edinburgh and London.'),
('De humani corporis fabrica', 'Andreas Vesalius', 'http://upload.wikimedia.org/wikipedia/commons/e/ee/Vesalius_Fabrica_fronticepiece.jpg', 'http://en.wikipedia.org/wiki/De_humani_corporis_fabrica', 'De humani corporis fabrica libri septem (Latin for On the fabric of the human body in seven books) is a set of books on human anatomy written by Andreas Vesalius (15141564) and published in 1543.'),
('Don Quixote', 'Miguel de Cervantes', 'http://upload.wikimedia.org/wikipedia/commons/6/69/Cervantes_Don_Quixote_1605.gif', 'http://en.wikipedia.org/wiki/Don_Quixote', 'Don Quixote (/ˌdɒnkiːˈhoʊtiː/; Spanish: [ˈdoŋ kiˈxote] (listen)), fully titled The Ingenious Gentleman Don Quixote of La Mancha (Spanish: El ingenioso hidalgo don Quijote de la Mancha), is a Spanish novel by Miguel de Cervantes Saavedra. It follows the adventures of Alonso Quixano, an hidalgo who reads so many chivalric novels that he decides to set out to revive chivalry, under the name Don Quixote. He recruits a simple farmer, Sancho Panza, as his squire, who often employs a unique, earthly wit in dealing with Don Quixotes rhetorical orations on antiquated knighthood. Don Quixote is met by the world as it is, initiating such themes as intertextuality, realism, metatheatre, and literary representation.'),
('Doria Atlas', 'Genoese military', 'https://iamwaywen.files.wordpress.com/2012/03/9.jpg', 'https://en.wikipedia.org/wiki/Doria_Atlas', 'The Doria Atlas is a 16th-century atlas commissioned by and named for the Genoese military leader Giovanni Andrea Doria. Likely compiled around 1570, it is a composite atlas featuring 186 printed and manuscript maps[1] from two distinct atlases of the Lafreri school.'),
('Geographia Cosmographia', 'Claudius Ptolemy', 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/La_Cosmographie_de_Claude_Ptolem%C3%A9e.djvu/page9-439px-La_Cosmographie_de_Claude_Ptolem%C3%A9e.djvu.jpg', 'http://en.wikipedia.org/wiki/Geography_(Ptolemy)', 'The Geography (Latin: Geographia, Cosmographia; Greek: Γεωγραφικὴ ὙφήγησιςGeographike Hyphegesis) is Ptolemys main work besides the Almagest. It is a treatise on cartography and a compilation of what was known about the worlds geography in the Roman Empire of the 2nd century. Ptolemy relied mainly on the work of an earlier geographer, Marinos of Tyre, and on gazetteers of the Roman and ancient Persian empire.'),
('Gospels of Henry the Lion - Original and only copy', 'Order of Saint Benedict', 'http://upload.wikimedia.org/wikipedia/commons/f/f8/Evangeliar_heinrich_des_loewen.jpg', 'http://en.wikipedia.org/wiki/Gospels_of_Henry_the_Lion', 'The Gospels of Henry the Lion were intended by Henry the Lion, Duke of Saxony, for the altar of the Virgin Mary in the church of St. Blaises Abbey, Brunswick, better known as Brunswick Cathedral. The volume is considered a masterpiece of Romanesque book illumination of the 12th century.'),
('Gutenberg Bible', 'Johann Gutenberg', 'http://upload.wikimedia.org/wikipedia/commons/2/27/Gutenberg_bible_Old_Testament_Epistle_of_St_Jerome.jpg', 'http://en.wikipedia.org/wiki/Gutenberg_Bible', 'The Gutenberg Bible (also known as the 42-line Bible, the Mazarin Bible or the B42) was the first major book printed in the West using movable type. It marked the start of the Gutenberg Revolution and the age of the printed book in the West. Widely praised for its high aesthetic and artistic qualities, the book has an iconic status. Written in Latin, the Gutenberg Bible is an edition of the Vulgate, printed by Johannes Gutenberg, in Mainz, Germany, in the 1450s. Forty-eight copies, or substantial portions of copies, survive, and they are considered to be among the most valuable books in the world, even though no complete copy has been sold since 1978. The 36-line Bible, believed to be the second printed version of the Bible, is also sometimes referred to as a Gutenberg Bible, but is likely the work of another printer.'),
('Les Liliacées', 'Pierre-Joseph Redouté', 'http://library.cincymuseum.org/bot/images/DSCN1955-full.JPG', 'http://en.wikipedia.org/wiki/Pierre-Joseph_Redout%C3%A9', 'Pierre-Joseph Redouté (10 July 1759 in Saint-Hubert, Belgium  19 June 1840 in Paris), was a Belgianpainter and botanist, known for his watercolours of roses, lilies and other flowers at Malmaison. He was nicknamed \"The Raphael of flowers\".'),
('Magna Carta - Original exemplar', 'John Lacland', 'http://upload.wikimedia.org/wikipedia/commons/e/ee/Magna_Carta_%28British_Library_Cotton_MS_Augustus_II.106%29.jpg', 'http://en.wikipedia.org/wiki/Magna_Carta', 'Magna Carta (Latin for Great Charter), also called Magna Carta Libertatum or The Great Charter of the Liberties of England, is an Angevincharter originally issued in Latin. It was sealed under oath by King John at Runnymede, on the bank of the River Thames near Windsor, England, on 15 June 1215.'),
('Mr. William Shakespeares Comedies, Histories & Tragedies (a.k.a. First Folio)', 'William Shakespeare', 'http://upload.wikimedia.org/wikipedia/commons/8/8c/Title_page_William_Shakespeare%27s_First_Folio_1623.jpg', 'http://en.wikipedia.org/wiki/First_Folio', 'Mr. William Shakespeares Comedies, Histories, & Tragedies is the 1623 published collection of William Shakespeares plays. Modern scholars commonly refer to it as the First Folio.'),
('Rothschild Prayerbook (a.k.a. Rothschild Hours)', '-', 'http://upload.wikimedia.org/wikipedia/commons/0/03/Rothschild2.jpg', 'http://en.wikipedia.org/wiki/Rothschild_Prayerbook', 'The Rothschild Prayerbook or Rothschild Hours (both are titles also used for other books), is an important Flemish illuminated manuscriptbook of hours, illuminated over the period c. 1500–20 by a number of artists. It has 254 folios, with a page size of 228 × 160 mm. It was once in the Austrian National Library in Vienna as Codex Vindobonensis S.N. 2844. Since its sale in 1999 it has held the world record price at auction for an illuminated manuscript. In 2014 it was purchased by Australian businessman Kerry Stokes from Christie\'s New York and is held in his private collection in Perth, Australia.'),
('Rules of basketball', 'James Naismith', 'http://a.espncdn.com/photo/2010/1027/pg2_naismith_576.jpg', 'http://en.wikipedia.org/wiki/Rules_of_basketball', 'The rules of basketball are the rules and regulations that govern the play, officiating, equipment and procedures of basketball. While many of the basic rules are uniform throughout the world, variations do exist. Most leagues or governing bodies in North America, the most important of which are the National Basketball Association and NCAA, formulate their own rules. In addition, the Technical Commission of the International Basketball Federation (FIBA) determines rules for international play.'),
('St Cuthbert Gospel', 'Unknown', 'http://upload.wikimedia.org/wikipedia/commons/5/57/St_Cuthbert_Gospel_-_f.1.jpg', 'http://en.wikipedia.org/wiki/St_Cuthbert_Gospel', 'The St Cuthbert Gospel, also known as the Stonyhurst Gospel or the St Cuthbert Gospel of St John, is a 7th-century pocket gospel book, written in Latin. Its finely decorated leather binding is the earliest known Western bookbinding to survive, and both the 94 vellumfolios and the binding are in outstanding condition for a book of this age. With a page size of only 138 by 92 millimetres (5.4 in × 3.6 in) the St Cuthbert Gospel is one of the smallest surviving Anglo-Saxon manuscripts. The essentially undecorated text is the Gospel of John in Latin, written in a script that has been regarded as a model of elegant simplicity.'),
('The Birds of America (1)', 'John James Audubon', 'http://upload.wikimedia.org/wikipedia/commons/3/39/Campephilus_principalisAWP066AA2.jpg', 'http://en.wikipedia.org/wiki/The_Birds_of_America', 'The Birds of America is a book by naturalist and painter John James Audubon, containing illustrations of a wide variety of birds of the United States. It was first published as a series in sections between 1827 and 1838, in Edinburgh and London.'),
('The Birds of America (2)', 'John James Audubon', 'http://upload.wikimedia.org/wikipedia/commons/5/50/Zenaida_macrouraAWP17AA.jpg', 'http://en.wikipedia.org/wiki/The_Birds_of_America', 'The Birds of America is a book by naturalist and painter John James Audubon, containing illustrations of a wide variety of birds of the United States. It was first published as a series in sections between 1827 and 1838, in Edinburgh and London.'),
('The Birds of America (3)', 'John James Audubon', 'http://upload.wikimedia.org/wikipedia/commons/9/9a/Audubon-Flamingo.jpg', 'http://en.wikipedia.org/wiki/The_Birds_of_America', 'The Birds of America is a book by naturalist and painter John James Audubon, containing illustrations of a wide variety of birds of the United States. It was first published as a series in sections between 1827 and 1838, in Edinburgh and London.'),
('The Canterbury Tales - First printed edition', 'Geoffrey Chaucer', 'http://upload.wikimedia.org/wikipedia/commons/8/80/Wife-of-Bath-ms.jpg', 'http://en.wikipedia.org/wiki/The_Canterbury_Tales', 'The Canterbury Tales (Middle English: Tales of Caunterbury) is a collection of over 20 stories written in Middle English by Geoffrey Chaucer at the end of the 14th century, during the time of the Hundred Years\' War. The tales (mostly written in verse, although some are in prose) are presented as part of a story-telling contest by a group of pilgrims as they travel together on a journey from Southwark to the shrine of Saint Thomas Becket at Canterbury Cathedral. The prize for this contest is a free meal at the Tabard Inn at Southwark on their return.'),
('The Federalist', 'Alexander Hamilton, John Jay, James Madison', 'http://upload.wikimedia.org/wikipedia/commons/2/23/Federalist.jpg', 'http://en.wikipedia.org/wiki/Federalist_Papers', 'The Federalist Papers are a series of 85 articles and essays written by Alexander Hamilton, James Madison, and John Jay promoting the ratification of the United States Constitution. Seventy-seven were published serially in The Independent Journal and The New York Packet between October of 1787 and August 1788. A compilation of these and eight others, called The Federalist; or, The New Constitution, was published in two volumes in 1788 by J. and A. McLean. The series\' correct title is The Federalist; the title The Federalist Papers did not emerge until the twentieth century.'),
('The First Book of Urizen', 'William Blake', 'http://upload.wikimedia.org/wikipedia/commons/e/e1/The_Book_of_Urizen%2C_copy_G_object_1_The_Book_of_Urizen.jpg', 'http://en.wikipedia.org/wiki/The_Book_of_Urizen', 'The Book of Urizen is one of the major prophetic books of the English writer William Blake, illustrated by Blake\'s own plates. It was originally published as The First Book of Urizen in 1794. Later editions dropped the \"First\". The book takes its name from the character Urizen in Blake\'s mythology, who represents alienated reason as the source of oppression. The book describes Urizen as the \"primeaval priest\" and tells how he became separated from the other Eternals to create his own alienated and enslaving realm of religious dogma. Los and Enitharmon create a space within Urizen\'s fallen universe to give birth to their son Orc, the spirit of revolution and freedom.'),
('The Tales of Beedle the Bard', 'J. K. Rowling', 'http://upload.wikimedia.org/wikipedia/en/2/25/The_Tales_of_Beedle_the_Bard.jpg', 'http://en.wikipedia.org/wiki/The_Tales_of_Beedle_the_Bard', 'The Tales of Beedle the Bard is a book of children\'s stories by British author J. K. Rowling. It purports to be the storybook of the same name mentioned in Harry Potter and the Deathly Hallows, the last book of the Harry Potter series.'),
('Traité des Arbres Fruitiers', 'Henri-Louis Duhamel du Monceau', 'http://upload.wikimedia.org/wikipedia/commons/d/d0/Pomme_rambour.jpg', 'http://en.wikipedia.org/wiki/Henri-Louis_Duhamel_du_Monceau', 'Henri-Louis Duhamel du Monceau (20 July 1700, Paris - 13 August 1782, Paris), was a French physician, naval engineer and botanist.'),
('United States Declaration of Independence', '', 'http://upload.wikimedia.org/wikipedia/commons/8/8f/United_States_Declaration_of_Independence.jpg', 'http://en.wikipedia.org/wiki/United_States_Declaration_of_Independence', 'The Declaration of Independence is the usual name of a statement adopted by the Continental Congress on July 4, 1776, which announced that the thirteen American colonies, then at war with Great Britain, regarded themselves as thirteen newly independent sovereign states, and no longer a part of the British Empire. Instead they formed a new nation—the United States of America. John Adams was a leader in pushing for independence, which was unanimously approved on July 2. A committee of five had already drafted the formal declaration, to be ready when Congress voted on independence. The term \"Declaration of Independence\" is not used in the document itself.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
