-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 01, 2024 at 09:29 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `finall`
--

-- --------------------------------------------------------

--
-- Table structure for table `painting`
--

CREATE TABLE `painting` (
  `Painting` text DEFAULT NULL,
  `Artist` text DEFAULT NULL,
  `Year of Painting` int(11) DEFAULT NULL,
  `Image` text DEFAULT NULL,
  `Painting Wikipedia Profile` text DEFAULT NULL,
  `Artist Wikipedia Profile` text DEFAULT NULL,
  `Description` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `painting`
--

INSERT INTO `painting` (`Painting`, `Artist`, `Year of Painting`, `Image`, `Painting Wikipedia Profile`, `Artist Wikipedia Profile`, `Description`) VALUES
('A Wheatfield with Cypresses', 'Vincent van Gogh', 1889, 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Vincent_Willem_van_Gogh_049.jpg/95px-Vincent_Willem_van_Gogh_049.jpg', 'http://en.wikipedia.org/wiki/A_Wheatfield_with_Cypresses', 'http://en.wikipedia.org/wiki/Vincent_van_Gogh', 'A Wheatfield with Cypresses (occasionally called A Cornfield with Cypresses) is any of three similar 1889 oil paintings by Vincent van Gogh, as part of his wheat field series. All were executed at the Saint-Paul-de-Mausole mental asylum at Saint-RÃ©my near Arles, France, where Van Gogh was voluntarily a patient from May 1889 to May 1890. The works were inspired by the view from the window at the asylum towards the Les Alpilles mountains.'),
('Garçon à la pipe', 'Pablo Picasso', 1905, 'http://uploads7.wikiart.org/images/pablo-picasso/acrobat-and-young-harlequin-1905.jpg', '-', '-', '-'),
('Adele Bloch-Bauer II', 'Gustav Klimt', 1912, 'http://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Gustav_Klimt_047.jpg/95px-Gustav_Klimt_047.jpg', 'http://en.wikipedia.org/wiki/Adele_Bloch-Bauer_II', '-', 'Adele Bloch-Bauer II is a 1912 painting by Gustav Klimt. Adele Bloch-Bauer was the wife of Ferdinand Bloch-Bauer, who was a wealthy industrialist who sponsored the arts and supported Gustav Klimt. Adele Bloch-Bauer was the only model to be painted twice by Klimt; she also appeared in the much more famous Portrait of Adele Bloch-Bauer I. Adele\'s portraits had hung in the family home prior to their seizure by the Nazis during WWII. The Austrian museum where they resided after the war was reluctant to return them to their rightful owners, hence a protracted court battle in the United States and in Austria (see Republic of Austria v. Altmann) ensued, which resulted in five Gustav Klimt paintings being returned to Maria Altmann, the niece of Ferdinand Bloch-Bauer, in January 2006. In November 2006, Christie\'s auction house sold Portrait of Adele Bloch-Bauer II at auction for almost $88 million, the fourth-highest priced piece of art at auction at the time.'),
('Anna\'s Light', 'Barnett Newman', 1968, 'http://artpaintingartist.org/wp-content/uploads/2014/02/Annas-Light-by-Barnett-Newman.jpg', '-', 'http://en.wikipedia.org/wiki/Barnett_Newman', '-'),
('Au Lapin Agile', 'Pablo Picasso', 1904, 'http://vineartshouston.files.wordpress.com/2012/05/picasso.jpg', '-', '-', '-'),
('Bal du moulin de la Galette', 'Pierre-Auguste Renoir', 1876, 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg/95px-Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg', 'http://en.wikipedia.org/wiki/Bal_du_moulin_de_la_Galette', 'http://en.wikipedia.org/wiki/Pierre-Auguste_Renoir', 'Bal du moulin de la Galette (commonly known as Dance at Le moulin de la Galette) is an 1876 painting by French artist Pierre-Auguste Renoir. It is housed at the MusÃ©e d\'Orsay in Paris and is one of Impressionisms most celebrated masterpieces. The painting depicts a typical Sunday afternoon at Moulin de la Galette in the district of Montmartre in Paris. In the late 19th century, working class Parisians would dress up and spend time there dancing, drinking, and eating galettes into the evening.:121-3'),
('Black Fire I', 'Barnett Newman', 1961, 'http://www.christies.com/media-library/images/salelandingpage/thumb/pwcmay2014/black-fire-index.jpg', '-', 'http://en.wikipedia.org/wiki/Barnett_Newman', '-'),
('Darmstadt Madonna', 'Hans Holbein', 1526, 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Darmstadtmadonna.jpg/95px-Darmstadtmadonna.jpg', 'http://en.wikipedia.org/wiki/Darmstadt_Madonna', 'http://en.wikipedia.org/wiki/Hans_Holbein', 'The Darmstadt Madonna (also known as the Madonna of Jakob Meyer zum Hasen) is an oil painting by Hans Holbein the Younger. Completed in 1526 in Basel, the work shows the BÃ¼rgermeister of Basel Jakob Meyer zum Hasen, his first wife (who had died earlier), his current wife, and his daughter grouped around the Madonna and infant Jesus. The meaning of the two other male figures on the left side is, like the overall iconography of the image, not entirely clear. The image testified to the resolutely Catholic faith of the BÃ¼rgermeister, who actively opposed the Reformation.'),
('Diana and Actaeon', 'Titian', 1556, 'http://www.nationalgallery.org.uk/upload/img/titian-diana-and-actaeon-NG6611-fm.jpg', 'http://en.wikipedia.org/wiki/Diana_and_Actaeon_(Titian)', '-', 'Diana and Actaeon is a painting by the Italian Renaissance master Titian, finished in 1556â€“1559, and is considered amongst Titian\'s greatest works. It portrays the moment in which the goddess Diana meets Actaeon. In 2008â€“2009, the National Gallery, London and National Gallery of Scotland successfully campaigned to acquire the painting from the Bridgewater Collection for Â£50 million. As a result, Diana and Actaeon will remain on display in the UK, and will alternate between the two galleries on five-year terms.'),
('Diana and Callisto', 'Titian', 1556, 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/TitianDianaCallistoEdinburgh.jpg/95px-TitianDianaCallistoEdinburgh.jpg', 'http://en.wikipedia.org/wiki/Diana_and_Callisto', '-', 'Diana and Callisto is a painting completed between 1556 and 1559 by the Venetian artist Titian. It portrays the moment in which the goddess Diana discovers that her maid Callisto has become pregnant by Jupiter. The painting was jointly purchased by the National Gallery and the National Galleries of Scotland for Â£45 million in March 2012. The painting is currently on display at the National Gallery in London. There is a later version by Titian and his workshop in the Kunsthistorisches Museum in Vienna.'),
('Dora Maar au Chat', 'Pablo Picasso', 1941, 'http://upload.wikimedia.org/wikipedia/en/c/c3/Dora_Maar_Au_Chat.jpg', 'http://en.wikipedia.org/wiki/Dora_Maar_au_Chat', 'http://en.wikipedia.org/wiki/Pablo_Picasso', 'Dora Maar au Chat (Dora Maar with Cat) is a 1941 painting by Pablo Picasso. It depicts Dora Maar, the painter\'s lover, seated on a chair with a small cat perched on her shoulders. This work is one of the world\'s most expensive paintings.'),
('Eagle Standing on Pine Tree', 'Qi Baishi', 1946, 'http://www.bloomberg.com/image/imPdF_xffcfE.jpg', '-', 'http://en.wikipedia.org/wiki/Qi_Baishi', '-'),
('Eight Elvises', 'Andy Warhol', 1963, 'http://upload.wikimedia.org/wikipedia/en/b/be/Eight_Elvises.jpg', 'http://en.wikipedia.org/wiki/Eight_Elvises', 'http://en.wikipedia.org/wiki/Andy_Warhol', 'Eight Elvises is a 1963 silkscreen painting by American pop artistAndy Warhol. In 2008 it was sold for $100 million to a private buyer, making the painting the most valuable work by Andy Warhol at the time. The current owner and location of the painting, which has not been seen publicly since the 1960s, are unknown.'),
('False Start', 'Jasper Johns', 1959, 'http://www.jasper-johns.org/images/paintings/false-start.jpg', '-', 'http://en.wikipedia.org/wiki/Jasper_Johns', '-'),
('Femme assise dans un jardin', 'Pablo Picasso', 1938, 'http://webneel.com/sites/default/files/images/manual/paint-exp/29-femme-assise-dans-un-jardin.jpg', '-', '-', '-'),
('Femme aux Bras Croisés', 'Pablo Picasso', 1902, 'http://upload.wikimedia.org/wikipedia/en/thumb/0/00/Pablo_Picasso%2C_1901-02%2C_Femme_aux_Bras_Crois%C3%A9s%2C_Woman_with_Folded_Arms_%28Madchenbildnis%29%2C_oil_on_canvas%2C_81_%C3%97_58_cm_%2832_%C3%97_23_in%29.jpg/95px-Pablo_Picasso%2C_1901-02%2C_Femme_aux_Bras_Crois%C3%A9s%2C_Woman_with_Folded_Arms_%28Madchenbildnis%29%2C_oil_on_canvas%2C_81_%C3%97_58_cm_%2832_%C3%97_23_in%29.jpg', 'http://en.wikipedia.org/wiki/Femme_aux_Bras_Crois%C3%A9s', '-', 'Femme aux Bras CroisÃ©s (Woman with Folded Arms), is a painting by Pablo Picasso done in 1902 during his Blue Period. The subject of the painting is unknown, but she may be an inmate of the Saint-Lazare hospital-prison in Paris.'),
('Flag', 'Jasper Johns', 1954, 'http://www.jasper-johns.org/images/paintings/flag.jpg', 'http://en.wikipedia.org/wiki/Flag_(painting)', 'http://en.wikipedia.org/wiki/Jasper_Johns', 'Flag is an encaustic painting by the American artist Jasper Johns. Created when Johns was 24 (1954â€“55), two years after he was discharged from the US Army, this painting was the first of many works that Johns has said were inspired by a dream of the U.S. flag in 1954. It is arguably the painting for which Johns is best known.'),
('Garçon à la pipe', 'Pablo Picasso', 1905, 'http://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Gar%C3%A7on_%C3%A0_la_pipe.jpg/95px-Gar%C3%A7on_%C3%A0_la_pipe.jpg', 'http://en.wikipedia.org/wiki/Gar%C3%A7on_%C3%A0_la_pipe', 'http://en.wikipedia.org/wiki/Pablo_Picasso', 'GarÃ§on Ã  la Pipe (English: Boy with a Pipe) is a painting by Pablo Picasso. It was painted in 1905 when Picasso was 24 years old, during his Rose Period, soon after he settled in the Montmartre section of Paris, France. The oil on canvas painting depicts a Parisian boy holding a pipe in his left hand and wearing a garland or wreath of flowers.'),
('Green Car Crash (Green Burning Car I)', 'Andy Warhol', 1963, 'http://www.thecityreview.com/s07cco1b.jpg', 'http://en.wikipedia.org/wiki/Green_Car_Crash', '-', 'Green Car Crash (Green Burning Car I) is a painting by the American artist Andy Warhol. In May 16, 2007 at 7 P.M, it sold for $71.7m (Â£42.3m) at auction.'),
('Irises', 'Vincent van Gogh', 1889, 'http://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/95px-Irises-Vincent_van_Gogh.jpg', 'http://en.wikipedia.org/wiki/Irises_(painting)', '-', 'Irises is one of many paintings and prints of irises by the Dutch artist Vincent van Gogh. Irises was painted while Vincent van Gogh was living at the asylum at Saint Paul-de-Mausole in Saint-RÃ©my-de-Provence, France, in the last year before his death in 1890.'),
('Le Bassin aux Nymphéas', 'Claude Monet', 1919, 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Le_bassin_aux_nymph%C3%A9as_-_Claude_Monet.jpg/95px-Le_bassin_aux_nymph%C3%A9as_-_Claude_Monet.jpg', 'http://en.wikipedia.org/wiki/Le_Bassin_Aux_Nymph%C3%A9as', 'http://en.wikipedia.org/wiki/Claude_Monet', 'Le Bassin Aux NymphÃ©as (Water Lily Pond; 1919) is one of the series of Water Lilies paintings by FrenchimpressionistartistClaude Monet. It is an oil on canvas painting measuring 100.4 Ã— 201 cm (39Â½ Ã— 79â…› in).'),
('Le Rêve', 'Pablo Picasso', 1932, 'http://upload.wikimedia.org/wikipedia/en/9/9d/Le-reve-1932.jpg', 'http://en.wikipedia.org/wiki/Le_R%C3%AAve_(painting)', 'http://en.wikipedia.org/wiki/Pablo_Picasso', 'Le RÃªve (French, \"The Dream\"\") is a 1932 oil painting (130 Ã— 97 cm) by Pablo Picasso'),
('Garçon à la pipe', 'Pablo Picasso', 1905, 'http://upload.wikimedia.org/wikipedia/en/3/34/Lesnoces.JPG', 'http://en.wikipedia.org/wiki/Les_Noces_de_Pierrette', 'http://en.wikipedia.org/wiki/Pablo_Picasso', 'Les Noces de Pierrette (English:The marriage of Pierrette) is a painting by the Spanish artist and sculptor, Pablo Picasso. Painted in 1905, during Picasso\'s Blue Period; a time when the artist faced poverty and depression following the suicide of his friend Carlos Casagemas in 1901.'),
('Massacre of the Innocents', 'Peter Paul Rubens', 1611, 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/0_Le_Massacre_des_Innocents_d%27apr%C3%A8s_P.P._Rubens_-_Mus%C3%A9es_royaux_des_beaux-arts_de_Belgique_%282%29.JPG/95px-0_Le_Massacre_des_Innocents_d%27apr%C3%A8s_P.P._Rubens_-_Mus%C3%A9es_royaux_des_beaux-arts_de_Belgique_%282%29.JPG', 'http://en.wikipedia.org/wiki/Massacre_of_the_Innocents_(Rubens)', 'http://en.wikipedia.org/wiki/Peter_Paul_Rubens', 'The Massacre of the Innocents is the subject of two paintings by Peter Paul Rubens depicting the episode of the biblical Massacre of the Innocents of Bethlehem, as related in the Gospel of Matthew.'),
('Men in Her Life', 'Andy Warhol', 1962, 'http://www.bloomberg.com/image/im9k1S6gOBdk.jpg', 'http://en.wikipedia.org/wiki/Men_in_Her_Life_(Painting)', '-', 'Men in Her Life is a 1962 painting by Andy Warhol. It is a black and white painting inspired by the life of Elizabeth Taylor, a seven foot tall creation of the artist.'),
('No 1 (Royal Red and Blue)', 'Mark Rothko', 1954, 'http://www.markrothko.org/wp-content/uploads/2014/07/No-1-royal-red-and-blue-Mark-Rothko.jpg', 'http://en.wikipedia.org/wiki/No_1_(Royal_Red_and_Blue)', '-', 'No 1 (Royal Red and Blue) is a 1954 Color Field painting by the Abstract expressionist artist Mark Rothko. In November 2012, the painting sold for US$75.1 million (Â£47.2m) at a Sotheby\'s auction.'),
('No. 5, 1948', 'Jackson Pollock', 1948, 'http://img.zanda.com/item/93060710000002/1024x768/No_5_1948.jpg', 'http://en.wikipedia.org/wiki/No._5,_1948', 'http://en.wikipedia.org/wiki/Jackson_Pollock', 'No. 5, 1948 is a painting by Jackson Pollock, an American painter known for his contributions to the abstract expressionist movement.'),
('Nude Sitting on a Divan', 'Amedeo Modigliani', 1917, 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Amedeo_Modigliani_063.jpg/95px-Amedeo_Modigliani_063.jpg', 'http://en.wikipedia.org/wiki/Nude_Sitting_on_a_Divan', 'http://en.wikipedia.org/wiki/Amedeo_Modigliani', 'Nude Sitting on a Divan (The Beautiful Roman Woman) is an oil on canvas painting by Italian artist Amedeo Modigliani depicting a partially draped woman seated with crossed legs against a warm red background. The work was one of a series of nudes painted by Modigliani in 1917 that created a sensation when exhibited in Paris that year. On November 2, 2010, the painting sold at a New York auction for $68.9 million, a record price for an artwork by Modigliani.'),
('Le Rêve', 'Pablo Picasso', 1932, 'http://upload.wikimedia.org/wikipedia/en/2/2b/Nude_Green_Leaves_and_Bust_by_Picasso.jpg', 'http://en.wikipedia.org/wiki/Nude,_Green_Leaves_and_Bust', 'http://en.wikipedia.org/wiki/Pablo_Picasso', 'Nude, Green Leaves and Bust (French: Nu au Plateau de Sculpteur) is a 1932 painting by Pablo Picasso, featuring his mistress Marie-ThÃ©rÃ¨se Walter.'),
('Orange, Red, Yellow', 'Mark Rothko', 1961, 'http://www.markrothko.org/images/paintings/orange-red-yellow.jpg', 'http://en.wikipedia.org/wiki/Orange,_Red,_Yellow', 'http://en.wikipedia.org/wiki/Mark_Rothko', 'Orange, Red, Yellow is a 1961 Color Field painting by Mark Rothko. It sold at Christies for $86,882,500 on May 8, 2012. The seller was the estate of David Pincus and the sale price represents a record nominal price for Post-War / contemporary art at public auction and for Rothko works in general.'),
('Peasant Woman Against a Background of Wheat', 'Vincent van Gogh', 1890, 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Vincent_Willem_van_Gogh_097.jpg/95px-Vincent_Willem_van_Gogh_097.jpg', 'http://en.wikipedia.org/wiki/Peasant_Woman_Against_a_Background_of_Wheat', '-', 'Peasant Woman Against a Background of Wheat is an 1890 painting by Vincent van Gogh. Van Gogh went on to paint several versions of this painting.'),
('Police Gazette', 'Willem de Kooning', 1955, 'http://webneel.com/daily/sites/default/files/images/daily/10-2013/27-most-expensive-painting-police-gazette.jpg', '-', '-', '-'),
('Portrait de l\'artiste sans barbe', 'Vincent van Gogh', 1889, 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Vincent_Willem_van_Gogh_102.jpg/95px-Vincent_Willem_van_Gogh_102.jpg', 'http://en.wikipedia.org/wiki/Self-Portraits_by_Vincent_van_Gogh', 'http://en.wikipedia.org/wiki/Vincent_van_Gogh', 'The dozens of self-portraits by Vincent van Gogh were an important part of his oeuvre as a painter. Vincent van Gogh (1853â€“1890) created many self-portraits during his lifetime. Most probably, Van Gogh\'s self-portraits are depicting the face as it appeared in the mirror he used to reproduce his face, i.e. his right side in the image is in reality the left side of his face.'),
('Portrait of a Halberdier', 'Pontormo', 1537, 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Pontormo_%28Jacopo_Carucci%29_%28Italian%2C_Florentine%29_-_Portrait_of_a_Halberdier_%28Francesco_Guardi%3F%29_-_Google_Art_Project.jpg/95px-Pontormo_%28Jacopo_Carucci%29_%28Italian%2C_Florentine%29_-_Portrait_of_a_Halberdier_%28Francesco_Guardi%3F%29_-_Google_Art_Project.jpg', '-', 'http://en.wikipedia.org/wiki/Pontormo', '-'),
('Portrait of Adele Bloch-Bauer I', 'Gustav Klimt', 1907, 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Gustav_Klimt_046.jpg/95px-Gustav_Klimt_046.jpg', 'http://en.wikipedia.org/wiki/Portrait_of_Adele_Bloch-Bauer_I', 'http://en.wikipedia.org/wiki/Gustav_Klimt', 'Portrait of Adele Bloch-Bauer I is a 1907 painting by Gustav Klimt. The first of two portraits Klimt painted of Bloch-Bauer, it has been referred to as the final and most fully representative work of his golden phase.'),
('Portrait of Alfonso d\'Avalos, Marquis of Vasto, in Armor with a Page', 'Titian', 1533, 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Titian_-_Marchese_del_Vasto.jpg/95px-Titian_-_Marchese_del_Vasto.jpg', '-', 'http://en.wikipedia.org/wiki/Titian', '-'),
('Portrait of Dr. Gachet', 'Vincent van Gogh', 1890, 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Portrait_of_Dr._Gachet.jpg/95px-Portrait_of_Dr._Gachet.jpg', 'http://en.wikipedia.org/wiki/Portrait_of_Dr._Gachet', 'http://en.wikipedia.org/wiki/Vincent_van_Gogh', 'Portrait of Dr. Gachet is one of the most revered paintings by the Dutch artist Vincent van Gogh. It depicts Dr. Paul Gachet who took care of Van Gogh during the final months of his life. There are two authenticated versions of the portrait, both painted in June 1890 at Auvers-sur-Oise. Both show Gachet sitting at a table and leaning his head on his right arm but they are easily differentiated in color and style. In 1990, the first version fetched a record price of $82.5 million ($75 million, plus a 10 percent buyer\'s commission) when sold at auction in New York. When accounting for inflation, this is still the highest price paid for art at a public auction.'),
('Portrait of Joseph Roulin', 'Vincent van Gogh', 1889, 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Vincent_van_Gogh_-_Portrait_of_Joseph_Roulin.jpg/95px-Vincent_van_Gogh_-_Portrait_of_Joseph_Roulin.jpg', '-', 'http://en.wikipedia.org/wiki/Vincent_van_Gogh', '-'),
('Rideau, Cruchon et Compotier', 'Paul CÃ©zanne', 1894, 'http://upload.wikimedia.org/wikipedia/en/thumb/8/82/Paulcezanneart.jpg/95px-Paulcezanneart.jpg', 'http://en.wikipedia.org/wiki/Rideau,_Cruchon_et_Compotier', '-', 'Rideau, Cruchon et Compotier is a painting created circa 1893 to 1894 by FrenchartistPaul CÃ©zanne (19 January 1839 â€“ 22 October 1906). It is considered the most expensivestill life ever sold at an auction.'),
('Salvator Mundi', 'Leonardo Da Vinci', 1490, 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Leonardo_da_Vinci_or_Boltraffio_%28attrib%29_Salvator_Mundi_circa_1500.jpg/95px-Leonardo_da_Vinci_or_Boltraffio_%28attrib%29_Salvator_Mundi_circa_1500.jpg', 'http://en.wikipedia.org/wiki/Salvator_Mundi_(Leonardo)', 'http://en.wikipedia.org/wiki/Leonardo_Da_Vinci', 'Salvator Mundi is a painting of Christ as Salvator Mundi recently attributed to Leonardo da Vinci, who is known to have painted the subject. It was lost and later rediscovered, and restored and exhibited in 2011. The painting shows Christ, in Renaissance garb, giving a benediction with his raised right hand and crossed fingers while holding a crystal sphere in his left hand.'),
('Silver Car Crash (Double Disaster)', 'Andy Warhol', 1963, 'http://www.theartwolf.com/news/images/warhol-silver-car-crash-double-disaster.jpg', 'http://en.wikipedia.org/wiki/Silver_Car_Crash_(Double_Disaster)', '-', 'Silver Car Crash (Double Disaster) is a 1963 painting by the American artist Andy Warhol. In November 2013 it sold for $105m (Â£65.5m) at auction, setting a new highest price for a painting by Warhol.'),
('Suprematist Composition', 'Kazimir Malevich', 1916, 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Suprematist_Composition_-_Kazimir_Malevich.jpg/95px-Suprematist_Composition_-_Kazimir_Malevich.jpg', 'http://en.wikipedia.org/wiki/Suprematist_Composition', 'http://en.wikipedia.org/wiki/Kazimir_Malevich', 'Suprematist Composition (blue rectangle over the red beam) is a painting by Kazimir Malevich, a Russian painter known as a pioneer of geometric abstraction. The painting represents a constellation of geometry and color in space with remarkable austerity.'),
('The Card Players', 'Paul CÃ©zanne', 1892, 'http://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Card_Players-Paul_Cezanne.jpg/95px-Card_Players-Paul_Cezanne.jpg', 'http://en.wikipedia.org/wiki/The_Card_Players', 'http://en.wikipedia.org/wiki/Paul_C%C3%A9zanne', 'The Card Players is a series of oil paintings by the French Post-Impressionist artist Paul CÃ©zanne. Painted during CÃ©zanne\'s final period in the early 1890s, there are five paintings in the series. The versions vary in size and in the number of players depicted. CÃ©zanne also completed numerous drawings and studies in preparation for The Card Players series. One version of The Card Players was sold in 2011 to the Royal Family of Qatar for a price variously estimated at between $250 million and $300 million, making it the most expensive work of art ever sold.'),
('The Gross Clinic', 'Thomas Eakins', 1875, 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Thomas_Eakins%2C_American_-_Portrait_of_Dr._Samuel_D._Gross_%28The_Gross_Clinic%29_-_Google_Art_Project.jpg/95px-Thomas_Eakins%2C_American_-_Portrait_of_Dr._Samuel_D._Gross_%28The_Gross_Clinic%29_-_Google_Art_Project.jpg', 'http://en.wikipedia.org/wiki/The_Gross_Clinic', 'http://en.wikipedia.org/wiki/Thomas_Eakins', 'The Gross Clinic, or, The Clinic of Dr. Gross, is an 1875 painting by American artist Thomas Eakins. It is oil on canvas and measures 8 feet (240 cm) by 6.5 feet (200 cm). Dr. Samuel D. Gross, a seventy-year-old professor dressed in a black frock coat, lectures a group of Jefferson Medical College students. Included among the group is a self-portrait of Eakins, who is seated to the right of the tunnel railing, sketching or writing. Seen over Dr. Gross\'s right shoulder is the clinic clerk, Dr. Franklin West, taking notes on the operation. Eakins\'s signature is painted into the painting, on the front of the surgical table.'),
('The Scream', 'Edvard Munch', 1895, 'http://upload.wikimedia.org/wikipedia/en/thumb/f/f7/The_Scream_Pastel.jpg/95px-The_Scream_Pastel.jpg', 'http://en.wikipedia.org/wiki/The_Scream', 'http://en.wikipedia.org/wiki/Edvard_Munch', 'The Scream (Norwegian: Skrik) is the popular name given to each of four versions of a composition, created as both paintings and pastels, by the Expressionist artist Edvard Munch between 1893 and 1910. Der Schrei der Natur (The Scream of Nature) is the title Munch gave to these works, all of which show a figure with an agonized expression against a landscape with a tumultuous orange sky. Arthur Lubow has described The Scream as \"an icon of modern art'),
('Three Studies for a Portrait of John Edwards', 'Francis Bacon', 1984, 'http://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2014/05/13/101669179-Untitled-4.530x298.jpg?v=1400076313', '-', '-', '-');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
